version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: "call_escalation_mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: call_escalation
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql_data: